PiesSandra/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace PiesSandra.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Orders");
        }

        public IActionResult Orders()
        {
            return View("Orders");
        }
        public IActionResult Users()
        {
            return View("Users");
        }
        public IActionResult Products()
        {
            return View("Products");
        }
        public IActionResult Roles()
        {
            return View("Roles");
        }
    }
}

PiesSandra/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using PiesSandra.Models;

namespace PiesSandra.Controllers
{
    public class AuthorizationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Select(int id)
        {
            if (id == 0)
                return View("SingIn");
            else
                return View("SingUp");
        }

        public IActionResult SingIn(User user)
        {
            return View("SingIn");
        }

        public IActionResult SingUp(User user)
        {
            return View("SingUp");
        }
    }
}

PiesSandra/Controllers/CompareController.cs
using Microsoft.AspNetCore.Mvc;

namespace PiesSandra.Controllers
{
    public class CompareController : Controller
    {

        private readonly IProductRepository productRepository;
        private readonly IComparisonRepository compareRepository;
        public CompareController(IProductRepository productRepository, IComparisonRepository compareRepository)
        {
            this.productRepository = productRepository;
            this.compareRepository = compareRepository;
        }

        public IActionResult Index()
        {
            var compare = compareRepository.TryGetByUserId(Constants.UserId);
            return View(compare);
        }

        public IActionResult Add(int id)
        {
            var product = productRepository.TryGetById(id);
            compareRepository.Add(product, Constants.UserId);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int id)
        {
            var product = productRepository.TryGetById(id);
            compareRepository.Remove(product, Constants.UserId);
            return RedirectToAction("Index");
        }
    }
}

PiesSandra/Views/Shared/Components/Cart/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PiesSandra.Controllers;

namespace PiesSandra.Views.Shared.ViewComponents.CartViewCpmponents
{
    public class CartViewComponent : ViewComponent
    {
        private readonly ICartRepository cartRepository;

        public CartViewComponent(ICartRepository cartRepository)
        {
            this.cartRepository = cartRepository;
        }

        public IViewComponentResult Invoke()
        {
            var cart = cartRepository.TryGetByUserId(Constants.UserId);
            var productCount = cart?.Amount;

            return View("Cart" ,productCount);
        }
    }
}

PiesSandra/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - PiesSandra - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

PiesSandra/Views/Shared/Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PiesSandra</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart @await Component.InvokeAsync("Cart")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Compare" asp-action="Index">Compare</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="SingIn">Sing In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="SingUp">Sing Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Administrator</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

PiesSandra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PiesSandra</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PiesSandra.styles.css" asp-append-version="true" />
</head>
<body>
    @await Html.PartialAsync("Header");

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("Footer");

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>